# Generated by Django 2.2.12 on 2020-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='atack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='typePokemon',
            field=models.CharField(default='No type', max_length=30),
        ),
    ]
