# Generated by Django 2.2.12 on 2020-07-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonAPI', '0002_auto_20200719_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='No name', max_length=30),
        ),
    ]
